font_family	JetBrains Mono Regular
bold_font	JetBrains Mono Bold
italic_font	JetBrains Mono Italic
bold_italic_font JetBrains Mono Bold Italic

font_size 12.0

background_opacity 0.75
dynamic_background_opacity 1
confirm_os_window_close 0

# Animated cursor
cursor_trail 1
cursor_blink_interval 0.75 ease-in-out
cursor_trail_decay 0.1 0.5

# change to x11 or wayland or leave auto
linux_display_server auto

scrollback_lines 2000
wheel_scroll_min_lines 1

enable_audio_bell no

window_padding_width 4

selection_foreground none
selection_background none
